ARG SSH_PUB_KEY=""
ARG ARCH_BASE=localhost/custom-arch
ARG ARCH_TAG=latest
FROM ${ARCH_BASE}:${ARCH_TAG}
ARG SSH_PUB_KEY
RUN echo ${SSH_PUB_KEY} > "/root/.ssh/authorized_keys"
CMD ["sleep", "infinity"]
