FROM docker.io/library/archlinux:latest AS arch_base

FROM arch_base AS arch_updated
RUN pacman -Syu --noconfirm --needed

FROM arch_updated AS base_packages
RUN pacman -S --noconfirm --needed \
	base-devel \
	neovim \
	git ripgrep fd \
	python \
	npm

FROM base_packages AS minimized
RUN pacman -Scc --noconfirm

FROM minimized
WORKDIR /workspace
CMD [ "sleep", "infinity" ]
