ARG ARCH_BASE=localhost/custom-arch
ARG ARCH_TAG=latest
FROM ${ARCH_BASE}:${ARCH_TAG} AS arch_base

FROM arch_base AS ansible_base
RUN pacman -S --noconfirm --needed \
	ansible-core

FROM ansible_base AS packages
RUN pacman -S --noconfirm --needed \
	podman git openssh

FROM packages AS galaxy
RUN ansible-galaxy collection install containers.podman

FROM galaxy
RUN mkdir ansible
WORKDIR ansible
CMD ["ansible-playbook", "-i", "inventories/hosts.yaml", "playbooks/deploy.yaml"]
